Mothballed

diff --git a/serfs/inkcertreq b/serfs/inkcertreq
--- a/serfs/inkcertreq
+++ b/serfs/inkcertreq
@@ -1,6 +1,5 @@
 #!/bin/bash
 #inkVerbSerf! verb.ink
-#set -e
 
 # This requests and gets certs via inkCert Proper for a given domain, including inkVerb namespace domains
 ## It applies only to one domain/subdomain at a time
@@ -34,7 +33,7 @@ DOMAIN=$1
 
 # Check inkCert installed
 if [ "${INKCERTINSTALLED}" = "NOT_YET" ]; then
-echo "inkCert not yet installed.
+/bin/echo "inkCert not yet installed.
 
 First run inkcertinstall
 "
@@ -43,7 +42,7 @@ fi
 
 # Verify that the domain is installed
 if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN} ]; then
-echo "Sorry, Bucko. ${DOMAIN} is not installed yet.
+/bin/echo "Sorry, Bucko. ${DOMAIN} is not installed yet.
 
 Do that first, then get back to me.
 "; exit 0
@@ -51,34 +50,67 @@ fi
 
 # Include and check the inkCert domain config
 . /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}
-if [ "${INKCERTED}" = "DONE_IC" ]; then
-echo "inkCert proper is already setup for ${DOMAIN}.
+inkcertmsg="This sets up certs for inkCert Proper."
+case ${INKCERTED} in
+  DONE_SC)
+  /bin/echo $inkcertmsg
+  /bin/echo "inkCert self-cert is already setup for ${DOMAIN}.
 
-To set up certs via Certbot or Letsencrypt, first run: inkcertrevoke ${DOMAIN}, then run this again.
-"
-exit 0
-fi
-if [ "${INKCERTED}" = "DONE_LE" ]; then
-echo "inkCert proper is already setup for ${DOMAIN}.
+  To set up certs differently, first run: inkcertrevokesc ${DOMAIN}, then run this again.
+  "
+  exit 0
+  ;;
+  DONE_IC)
+  /bin/echo $inkcertmsg
+  /bin/echo "inkCert Proper is already setup for ${DOMAIN}.
 
-To set up certs via Certbot or inkCert Proper, first run: inkcertrevoke ${DOMAIN}, then run this again.
-"
-exit 0
-fi
-if [ "${INKCERTED}" = "DONE_CB" ]; then
-echo "inkCert proper is already setup for ${DOMAIN}.
+  To set up certs differently, first run: inkcertrevoke ${DOMAIN}, then run this again.
+  "
+  exit 0
+  ;;
+  DONE_LE)
+  /bin/echo $inkcertmsg
+  /bin/echo "inkCert Letsencrypt is already setup for ${DOMAIN}.
 
-To set up certs via Letsencrypt or inkCert Proper, first run: inkcertrevoke ${DOMAIN}, then run this again.
-"
-exit 0
-fi
+  To set up certs differently, first run: inkcertrevokele ${DOMAIN}, then run this again.
+  "
+  exit 0
+  ;;
+  DONE_CB)
+  /bin/echo $inkcertmsg
+  /bin/echo "inkCert cert-bot is already setup for ${DOMAIN}.
+
+  To set up certs differently, first run: inkcertrevokecb ${DOMAIN}, then run this again.
+  "
+  exit 0
+  ;;
+  DONE_CBDIGOC)
+  /bin/echo $inkcertmsg
+  /bin/echo "inkCert certbot for DigitalOcean is already setup for ${DOMAIN}.
+
+  To set up certs differently, first run: inkcertrevokecbdigoc ${DOMAIN}, then run this again.
+  "
+  exit 0
+  ;;
+  NO|NOT_YET)
+    /bin/echo "Ready to go..."
+  ;;
+  *)
+    if ! /bin/grep -q "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}; then
+      /bin/echo "Something's wrong with the inkCert siteinkcert. configs! Aborting."
+      exit 6
+    else
+      /bin/echo "Ready to go..."
+    fi
+  ;;
+esac
 
 
 # Check for verb domain and status
 ## If verb domain was spelled correctly
 if [[ "${DOMAIN}" =~ ".verb.email" ]] || [[ "${DOMAIN}" =~ ".verb.one" ]] || [[ "${DOMAIN}" =~ ".verb.ink" ]] || [[ "${DOMAIN}" =~ ".verb.blue" ]] || [[ "${DOMAIN}" =~ ".verb.vip" ]] || [[ "${DOMAIN}" =~ ".verb.kiwi" ]] || [[ "${DOMAIN}" =~ ".verb.red" ]] || [[ "${DOMAIN}" =~ ".verb.rocks" ]]; then
  if [[ "${DOMAIN}" != *"${SITENAME}"* ]]; then
-echo "
+/bin/echo "
 Problem: You might have spelled ${DOMAIN} wrong.
   - Did you mean to include "${SITENAME}"?
   - Are you an awesome person with multiple inkVerb namespaces, but you somehow have the wrong server?
@@ -89,7 +121,7 @@ fi
 ## Check specific verb domain tlds
 ### Create the error message function
 verbtld_is_off() {
-echo "
+/bin/echo "
 Problem: ${DOMAIN} is not active on this server...
   1. It could be running on a different Verber server. If so, run inkCert on that server.
   2. You could have planned it for this Verber server, but it's not on. Activate on this server with verbon
@@ -158,10 +190,10 @@ fi
 
 # Verify the certs
 if [ ! -d /etc/inkcert/live/${DOMAIN} ]; then
-echo "Big error! Unable to get the certs from the cert authority. Can't continue."; exit 4
+/bin/echo "Big error! Unable to get the certs from the cert authority. Can't continue."; exit 4
 fi
 
 # Finish
-echo "
+/bin/echo "
 Finished getting certs. Now to install them with inkcertadd...
 "
