Dev-Production Rotation

diff --git a/serfs/inkcertreq b/serfs/inkcertreq
--- a/serfs/inkcertreq
+++ b/serfs/inkcertreq
@@ -1,6 +1,6 @@
 #!/bin/bash
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This requests and gets certs via inkCert Proper for a given domain, including inkVerb namespace domains
 ## It applies only to one domain/subdomain at a time
@@ -28,9 +28,9 @@ set -e
 DOMAIN=$1
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
-. /var/local/verb/configs/inkcert/inkcertstatus
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
+. /opt/verb/conf/inkcert/inkcertstatus
 
 # Check inkCert installed
 if [ "${INKCERTINSTALLED}" = "NOT_YET" ]; then
@@ -42,7 +42,7 @@ exit 0
 fi
 
 # Verify that the domain is installed
-if [ ! -f /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${DOMAIN} ]; then
+if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN} ]; then
 echo "Sorry, Bucko. ${DOMAIN} is not installed yet.
 
 Do that first, then get back to me.
@@ -50,25 +50,25 @@ Do that first, then get back to me.
 fi
 
 # Include and check the inkCert domain config
-. /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${DOMAIN}
+. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}
 if [ "${INKCERTED}" = "DONE_IC" ]; then
- if [ "$2" = "r" ]; then
-echo "Refreshing inkCert Proper certs to include any subdomains of ${DOMAIN} since the last renewal. Don't do this too often."
- else
-
 echo "inkCert proper is already setup for ${DOMAIN}.
 
-To set up certs via Letsencrypt, first run: inkcertrevoke ${DOMAIN}, then run this again.
-
-If you wish to refresh the certificate, such as to include a newly added subdomain, run with \"r\" at the end of the command. See instructions for this Serf."
+To set up certs via Certbot or Letsencrypt, first run: inkcertrevoke ${DOMAIN}, then run this again.
+"
 exit 0
- fi
 fi
-
 if [ "${INKCERTED}" = "DONE_LE" ]; then
-echo "inkCert is already setup for ${DOMAIN} with Letsencrypt.
+echo "inkCert proper is already setup for ${DOMAIN}.
 
-To set up certs for inkCert proper, first fun inkcertrevokele ${DOMAIN}, then run this again.
+To set up certs via Certbot or inkCert Proper, first run: inkcertrevoke ${DOMAIN}, then run this again.
+"
+exit 0
+fi
+if [ "${INKCERTED}" = "DONE_CB" ]; then
+echo "inkCert proper is already setup for ${DOMAIN}.
+
+To set up certs via Letsencrypt or inkCert Proper, first run: inkcertrevoke ${DOMAIN}, then run this again.
 "
 exit 0
 fi
@@ -76,7 +76,7 @@ fi
 
 # Check for verb domain and status
 ## If verb domain was spelled correctly
-if [[ "${DOMAIN}" =~ ".verb.email" ]] || [[ "${DOMAIN}" =~ ".verb.one" ]] || [[ "${DOMAIN}" =~ ".verb.ink" ]] || [[ "${DOMAIN}" =~ ".verb.blue" ]] || [[ "${DOMAIN}" =~ ".verb.guru" ]] || [[ "${DOMAIN}" =~ ".verb.kiwi" ]] || [[ "${DOMAIN}" =~ ".verb.red" ]] || [[ "${DOMAIN}" =~ ".verb.rocks" ]]; then
+if [[ "${DOMAIN}" =~ ".verb.email" ]] || [[ "${DOMAIN}" =~ ".verb.one" ]] || [[ "${DOMAIN}" =~ ".verb.ink" ]] || [[ "${DOMAIN}" =~ ".verb.blue" ]] || [[ "${DOMAIN}" =~ ".verb.vip" ]] || [[ "${DOMAIN}" =~ ".verb.kiwi" ]] || [[ "${DOMAIN}" =~ ".verb.red" ]] || [[ "${DOMAIN}" =~ ".verb.rocks" ]]; then
  if [[ "${DOMAIN}" != *"${SITENAME}"* ]]; then
 echo "
 Problem: You might have spelled ${DOMAIN} wrong.
@@ -97,9 +97,14 @@ Problem: ${DOMAIN} is not active on this server...
 "; exit 0;
 }
 ### Do the checks per each verb tld
-. /var/local/verb/configs/sitetldstatus
+. /opt/verb/conf/sitetldstatus
 if [ "${DOMAIN}" = "${emailURI}" ]; then
  if [[ "${VERBemail}" != true ]]; then
+  verbtld_is_off
+ fi
+fi
+if [ "${DOMAIN}" = "${cityURI}" ]; then
+ if [[ "${VERBcity}" != true ]]; then
   verbtld_is_off
  fi
 fi
@@ -118,8 +123,8 @@ if [ "${DOMAIN}" = "${blueURI}" ]; then
   verbtld_is_off
  fi
 fi
-if [ "${DOMAIN}" = "${guruURI}" ]; then
- if [[ "${VERBguru}" != true ]]; then
+if [ "${DOMAIN}" = "${vipURI}" ]; then
+ if [[ "${VERBvip}" != true ]]; then
   verbtld_is_off
  fi
 fi
@@ -143,11 +148,6 @@ if [ "${DOMAIN}" = "${rocksURI}" ]; then
   verbtld_is_off
  fi
 fi
-if [ "${DOMAIN}" = "${unoURI}" ]; then
- if [[ "${VERBuno}" != true ]]; then
-  verbtld_is_off
- fi
-fi
 
 # Get the certs
 ## This is the place to request and/or install the certs with the automated inkCert Proper script.
@@ -158,11 +158,10 @@ fi
 
 # Verify the certs
 if [ ! -d /etc/inkcert/live/${DOMAIN} ]; then
-echo "Big error! Unable to get the certs from the cert authority. Can't continue."; exit 44
+echo "Big error! Unable to get the certs from the cert authority. Can't continue."; exit 4
 fi
 
 # Finish
 echo "
 Finished getting certs. Now to install them with inkcertadd...
 "
-
diff --git a/serfs/inkcertreqle b/serfs/inkcertreqle
--- a/serfs/inkcertreqle
+++ b/serfs/inkcertreqle
@@ -1,6 +1,6 @@
 #!/bin/bash
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This requests and gets Letsencrypt certs via inkCert-Letsencrypt for a given domain, including inkVerb namespace domains
 ## It also applies to all subdomains for that domain
@@ -21,9 +21,9 @@ set -e
 DOMAIN=$1
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
-. /var/local/verb/configs/inkcert/inkcertstatus
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
+. /opt/verb/conf/inkcert/inkcertstatus
 
 # Check inkCert installed
 if [ "${INKCERTINSTALLED}" = "NOT_YET" ]; then
@@ -35,7 +35,7 @@ exit 0
 fi
 
 # Verify that the domain is installed
-if [ ! -f /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${DOMAIN} ]; then
+if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN} ]; then
 echo "Sorry, Bucko. ${DOMAIN} is not installed yet.
 
 Do that first, then get back to me.
@@ -43,32 +43,32 @@ Do that first, then get back to me.
 fi
 
 # Include and check the inkCert domain config
-. /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${DOMAIN}
+. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}
 if [ "${INKCERTED}" = "DONE_IC" ]; then
 echo "inkCert proper is already setup for ${DOMAIN}.
 
-To set up certs via Letsencrypt, first run: inkcertrevoke ${DOMAIN}, then run this again.
+To set up certs via Certbot or Letsencrypt, first run: inkcertrevoke ${DOMAIN}, then run this again.
 "
 exit 0
 fi
-
 if [ "${INKCERTED}" = "DONE_LE" ]; then
- if [ "$2" = "r" ]; then
-echo "Refreshing Let's Encrypt certs to include any subdomains of ${DOMAIN} since the last renewal. Don't do this too often."
- else
-echo "inkCert is already setup for ${DOMAIN} with Letsencrypt.
+echo "inkCert proper is already setup for ${DOMAIN}.
 
-To set up certs for inkCert proper, run: inkcertdo ${DOMAIN}
-
-If you wish to refresh the certificate, such as to include a newly added subdomain, run with \"r\" at the end of the command. See instructions for this Serf.
+To set up certs via Certbot or inkCert Proper, first run: inkcertrevoke ${DOMAIN}, then run this again.
 "
 exit 0
- fi
+fi
+if [ "${INKCERTED}" = "DONE_CB" ]; then
+echo "inkCert proper is already setup for ${DOMAIN}.
+
+To set up certs via Letsencrypt or inkCert Proper, first run: inkcertrevoke ${DOMAIN}, then run this again.
+"
+exit 0
 fi
 
 # Check for verb domain and status
 ## If verb domain was spelled correctly
-if [[ "${DOMAIN}" =~ ".verb.email" ]] || [[ "${DOMAIN}" =~ ".verb.one" ]] || [[ "${DOMAIN}" =~ ".verb.ink" ]] || [[ "${DOMAIN}" =~ ".verb.blue" ]] || [[ "${DOMAIN}" =~ ".verb.guru" ]] || [[ "${DOMAIN}" =~ ".verb.kiwi" ]] || [[ "${DOMAIN}" =~ ".verb.red" ]] || [[ "${DOMAIN}" =~ ".verb.rocks" ]]; then
+if [[ "${DOMAIN}" =~ ".verb.email" ]] || [[ "${DOMAIN}" =~ ".verb.one" ]] || [[ "${DOMAIN}" =~ ".verb.ink" ]] || [[ "${DOMAIN}" =~ ".verb.blue" ]] || [[ "${DOMAIN}" =~ ".verb.vip" ]] || [[ "${DOMAIN}" =~ ".verb.kiwi" ]] || [[ "${DOMAIN}" =~ ".verb.red" ]] || [[ "${DOMAIN}" =~ ".verb.rocks" ]]; then
  if [[ "${DOMAIN}" != *"${SITENAME}"* ]]; then
 echo "
 Problem: You might have spelled ${DOMAIN} wrong.
@@ -89,9 +89,14 @@ Problem: ${DOMAIN} is not active on this server...
 "; exit 0;
 }
 ### Do the checks per each verb tld
-. /var/local/verb/configs/sitetldstatus
+. /opt/verb/conf/sitetldstatus
 if [ "${DOMAIN}" = "${emailURI}" ]; then
  if [[ "${VERBemail}" != true ]]; then
+  verbtld_is_off
+ fi
+fi
+if [ "${DOMAIN}" = "${cityURI}" ]; then
+ if [[ "${VERBcity}" != true ]]; then
   verbtld_is_off
  fi
 fi
@@ -110,8 +115,8 @@ if [ "${DOMAIN}" = "${blueURI}" ]; then
   verbtld_is_off
  fi
 fi
-if [ "${DOMAIN}" = "${guruURI}" ]; then
- if [[ "${VERBguru}" != true ]]; then
+if [ "${DOMAIN}" = "${vipURI}" ]; then
+ if [[ "${VERBvip}" != true ]]; then
   verbtld_is_off
  fi
 fi
@@ -135,11 +140,6 @@ if [ "${DOMAIN}" = "${rocksURI}" ]; then
   verbtld_is_off
  fi
 fi
-if [ "${DOMAIN}" = "${unoURI}" ]; then
- if [[ "${VERBuno}" != true ]]; then
-  verbtld_is_off
- fi
-fi
 
 # Stop Apache
 apache2ctl graceful-stop; wait
@@ -148,7 +148,9 @@ systemctl stop apache2; wait
 # Get the certs
 ##NOTE make the system wait before and after Letsencrypt because sometimes LE can stumble over it's own feet.
 sleep 1
-letsencrypt certonly --standalone --expand --keep-until-expiring -c /var/local/verb/configs/inkcert/cli-ini/cli.${DOMAIN}.ini
+## We need `yes n |` because the salesmen want to break the script with email solicitation
+yes n | certbot --apache certonly --expand --renew-by-default -c /opt/verb/conf/inkcert/cli-ini/cli.${DOMAIN}.ini
+wait
 sleep 1
 # the --quiet / -q option doesn't seem to work
 # Additional options if not doing certonly: --no-redirect --no-hsts --no-uir
@@ -161,11 +163,10 @@ systemctl start apache2; wait
 
 # Verify the certs
 if [ ! -d /etc/inkcert/le/live/${DOMAIN} ]; then
-echo "Big error! Unable to get the certs from the cert authority. Can't continue."; exit 44
+echo "Big error! Unable to get the certs from the cert authority. Can't continue."; exit 4
 fi
 
 # Finish
 echo "
 Finished getting certs. Now to install them with inkcertaddle...
 "
-
diff --git a/serfs/installampache b/serfs/installampache
--- a/serfs/installampache
+++ b/serfs/installampache
@@ -1,6 +1,6 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This installs Ampache from inkisaverb.com/repo and links it to ampache....verb.kiwi
 
@@ -13,12 +13,29 @@ set -e
 CVAPPNAME=ampache
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
 
 DBASE=$1
 DBUSER=$2
 DBPASSWORD=$3
+
+# Install
+cd /var/www/vapps
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/html/kiwi.ampache; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
 
 # Auto database
 if [ -z ${3} ]; then
@@ -28,17 +45,8 @@ DBASE=${CVAPPNAME}$(pwgen -s -1 6); fi
 if [ -z ${2} ]; then
 DBUSER=${DBASE}; fi
 
-# Install
-cd /var/www/vapps
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
-rm -rf /var/www/html/kiwi.ampache
-ln -s /var/www/vapps/${CVAPPNAME} /var/www/html/kiwi.ampache
-chown -R www-data:www-data /var/www/html/kiwi.ampache
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
-
 # Create the database user and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON *.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}' WITH GRANT OPTION;
 FLUSH PRIVILEGES;"
@@ -50,13 +58,13 @@ FLUSH PRIVILEGES;"
 #sed -i "s/database_username = username/database_username = ${DBUSER}/g" /var/www/vapps/ampache/config/ampache.cfg.php
 #sed -i "s/database_password = password/database_password = ${DBPASSWORD}/g" /var/www/vapps/ampache/config/ampache.cfg.php
 ## Add the tables to the database
-#mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf ${DBASE} < /var/www/vapps/ampache/sql/ampache.sql
+#mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf ${DBASE} < /var/www/vapps/ampache/sql/ampache.sql
 
 # Write the config for backup
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}
 
 echo "These are setup:
 
diff --git a/serfs/installfossil b/serfs/installfossil
--- a/serfs/installfossil
+++ b/serfs/installfossil
@@ -1,8 +1,8 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
-# This installs fossil to be available at fossil.your-name.verb.guru/...
+# This installs fossil to be available at fossil.your-name.verb.vip/...
 
 # How to use:
 ## ./installfossil [username] [user-email] [userpassword]
@@ -11,43 +11,62 @@ set -e
 ## ./installfossil adam adam@verb.ink Adamp4$$w0RD
 
 
+CVAPPNAME=fossil
+
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
 
 NEWUSER=$1
 NEWEMAIL=$2
 NEWPASS=$3
 
+
+cd /var/www/vapps
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+rm -f ${CVAPPNAME}
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+
+rm -f /usr/bin/fossil
+mv /var/www/vapps/fossil /usr/bin
+fossil all rebuild
+
 # Install and set up directories
-apt install -y fossil
-mkdir /var/www/guru/fossil
-rm -rf /var/www/html/guru.fossil
-ln -s /var/www/guru/fossil /var/www/html/guru.fossil
-chown -R www-data:www-data  /var/www/html
-chown -R www-data:www-data /var/www/guru
+mkdir -p /var/www/vip/fossil
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}
+chown -R www-data:www-data  /var/www/html/vip.fossil
+chown -R www-data:www-data /var/www/vip
 
 # Create the first default fossil
-cd /var/www/guru/fossil
-fossil new index.fossil
-chown www-data:www-data index.fossil
+cd /var/www/vip/fossil
+fossil new index.fossil; wait
+chown www-data:www-data index.fossil; wait
 echo "#!/usr/bin/fossil
 repository: /fossil/index.fossil
 
 # If you didn't figure it out, your first fossil is called index.fossil.
 # Change the .fossil file name on line 2 of this file to have the default url point to any .fossil file you want.
 # dinosaur.fossil is an example of another .fossil file." > index.cgi
-chmod +x index.cgi
+chmod 750 index.cgi
 
 # Create a second demo fossil, dinosaur
-cd /var/www/guru/fossil
+cd /var/www/vip/fossil
 fossil new dinosaur.fossil
 echo "#!/usr/bin/fossil
 repository: /fossil/dinosaur.fossil" > dinosaur.cgi
-chmod +x dinosaur.cgi
+chmod 750 dinosaur.cgi
 
 # Final chown to allow database to be writable
-chown -R www-data:www-data /var/www/guru/fossil
+chown -R www-data:www-data /var/www/vip/fossil; wait
 
 # Add the user
 fossil user new ${NEWUSER} ${NEWEMAIL} ${NEWPASS} --repository index.fossil
@@ -56,10 +75,10 @@ fossil user new ${NEWUSER} ${NEWEMAIL} ${NEWPASS} --repository dinosaur.fossil
 # Ending message
 echo "
 Fossil installed. The first, default fossil will be available at:
-fossil.${guruURI}
+fossil.${vipURI}
 
 The another demo fossil, dinosaur.fossil, is available at:
-fossil.${guruURI}/dinosaur.cgi
+fossil.${vipURI}/dinosaur.cgi
 
-All relevant files appear via ftp in the \"guru/fossil\" folder.
+All relevant files appear via ftp in the \"vip/fossil\" folder.
 "
diff --git a/serfs/installiwpadmin b/serfs/installiwpadmin
--- a/serfs/installiwpadmin
+++ b/serfs/installiwpadmin
@@ -1,53 +1,70 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs the InfiniteWP Server to a new directory to an existing domain in the .../html/ folder
 ## For security, this does NOT install to a pre-defined inkVerb subdomain, ie iwp.name.verb.ink. The site has too much control and must be set differently.
 ## This does not interfere at all with the contents of the domain.
 ## This should be installed AFTER any installations to the domain, such as WordPress
 
-# All options after the domain are optional, but are sequential
+# All options after the email are optional, but are sequential
 
 # How to use:
-## ./installiwpadmin [sub.domain.tld or domain.tld] [directory of domain.tld/directory] [dbase] [dbuser] [dbpassword]
+## ./installiwpadmin [sub.domain.tld or domain.tld] [email for registration] [directory of domain.tld/directory] [dbase] [dbuser] [dbpassword]
 
 
 CVAPPNAME=iwpadmin
 
 DOMAIN=$1
-DIRECTORY=$2
-DBASE=$3
-DBUSER=$4
-DBPASSWORD=$5
+REMAIL=$2
+DIRECTORY=$3
+DBASE=$4
+DBUSER=$5
+DBPASSWORD=$6
 CLEANNAME=$(echo $DOMAIN | sed -e 's/\.//g')
 
 # Check that the directory doesn't already exist
 if [ -d /var/www/html/${DOMAIN}/${DIRECTORY} ]; then
 echo "That directory already exists for that domain. Choose a different directory."
-exit 22; fi
+exit 8; fi
 
 # Options
 if [ -z ${1} ]; then
 echo "You must designate a domain."
-exit 22; fi
-## Auto options
+exit 8; fi
+
+# Check email is set
 if [ -z ${2} ]; then
-DIRECTORY=iwp$(pwgen -s -1 1); fi
-if [ -z ${5} ]; then
-DBPASSWORD=$(pwgen -s -1 10); fi
-if [ -z ${3} ]; then
-DBASE=iwp$(echo $CLEANNAME | cut -c1-23)$(pwgen -s -1 5); fi
-if [ -z ${4} ]; then
-DBUSER=${DBASE}; fi
+echo "You must set an email for the repo package in InfiniteWP-Admin."
+exit 8; fi
+
 
 # Include the config file
-. /var/local/verb/configs/sitenameip
+. /opt/verb/conf/sitenameip
 
 # Download and establish IWPAdmin in the server to pre-created domain
 cd /var/www/vapps
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
+/opt/verb/serfs/inkget ${CVAPPNAME} ${REMAIL}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+## Auto options
+if [ -z ${3} ]; then
+DIRECTORY=iwp$(pwgen -s -1 1); fi
+if [ -z ${6} ]; then
+DBPASSWORD=$(pwgen -s -1 10); fi
+if [ -z ${4} ]; then
+DBASE=iwp$(echo $CLEANNAME | cut -c1-23)$(pwgen -s -1 5); fi
+if [ -z ${5} ]; then
+DBUSER=${DBASE}; fi
+
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
 mv ${CVAPPNAME} ${DOMAIN}
 mv ${CVAPPNAME} ${CVAPPNAME}.${DOMAIN}
 ln -sfn /var/www/vapps/${CVAPPNAME}.${DOMAIN} /var/www/html/${DOMAIN}/${DIRECTORY}
@@ -63,10 +80,10 @@ echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
 APPDDBPAS=${DBPASSWORD}
-IWPADMIN_DIRECTORY=\"${DIRECTORY}\"" > /var/local/verb/configs/vapp.${CVAPPNAME}.${DOMAIN}
+IWPADMIN_DIRECTORY=\"${DIRECTORY}\"" > /opt/verb/conf/vapp.${CVAPPNAME}.${DOMAIN}
 
 # Reset all permissions
-chown -R www-data:www-data /var/www/html/${DOMAIN}/${DIRECTORY}
+chown -R www-data:www-data /var/www/html/${DOMAIN}/${DIRECTORY}; wait
 
 echo "${DOMAIN} now has the InfiniteWP Admin Panel.
 These are setup:
diff --git a/serfs/installmediawiki b/serfs/installmediawiki
--- a/serfs/installmediawiki
+++ b/serfs/installmediawiki
@@ -1,6 +1,6 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs MediaWiki from the inkisaverb.com repository and links it to wiki.your-name.verb.ink
 
@@ -13,8 +13,8 @@ set -e
 CVAPPNAME=mediawiki
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
 
 DBASE=$1
 DBUSER=$2
@@ -22,9 +22,26 @@ DBPASSWORD=$3
 CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')
 
 # Check if already installed
-if [-f /var/local/verb/configs/vapp.${CVAPPNAME} ]; then
+if [-f /opt/verb/conf/vapp.${CVAPPNAME} ]; then
 echo "This is already installed. I quit."
 exit 0; fi
+
+# Download and establish mediawiki from the inkVerb repo
+cd /var/www/vapps
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/html/ink.wiki; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
 
 # Auto database
 if [ -z ${3} ]; then
@@ -34,17 +51,8 @@ DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
 if [ -z ${2} ]; then
 DBUSER=${DBASE}; fi
 
-# Download and establish mediawiki from the inkVerb repo
-cd /var/www/vapps
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
-rm -rf /var/www/html/ink.wiki
-ln -sfn /var/www/vapps/${CVAPPNAME} /var/www/html/ink.wiki
-chown -R www-data:www-data /var/www/html/ink.wiki
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
-
 # Create the database and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
 FLUSH PRIVILEGES;"
@@ -53,7 +61,7 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}
 
 echo "These are setup:
 
@@ -67,6 +75,6 @@ Return email address: use anything real, maybe yourname@${inkURI}, NOT something
 
 Go to http://wiki.${inkURI} to install.
 
-After installing, download the LocalSettings.php file, then upload it to the "guru" web folder, then run postinstallmediawiki to complete in installation.
+After installing, download the LocalSettings.php file, then upload it to the \"vip\" web folder, then run postinstallmediawiki to complete in installation.
 "
 
diff --git a/serfs/installnet2ftp b/serfs/installnet2ftp
--- a/serfs/installnet2ftp
+++ b/serfs/installnet2ftp
@@ -1,9 +1,9 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
-# This downloads and installs net2ftp manually from inkisaverb.com/repo and linnks it to net2ftp....verb.guru
-# Prereq: vsftp and an ftpguru or ftpfiler for login
+# This downloads and installs net2ftp manually from inkisaverb.com/repo and linnks it to net2ftp....verb.vip
+# Prereq: vsftp and an ftpvip or ftpfiler for login
 
 # How to use:
 ## ./installvsftpd
@@ -12,17 +12,25 @@ set -e
 CVAPPNAME=net2ftp
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
 
 # Download and unpack
 cd /var/www/vapps
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
-rm -rf /var/www/html/guru.net2ftp
-ln -s /var/www/vapps/net2ftp /var/www/html/guru.net2ftp
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
-chown -R www-data:www-data /var/www/html/guru.net2ftp
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/html/vip.net2ftp; wait
 
 # Settings
 cd net2ftp
@@ -40,7 +48,7 @@ sed -i "s/\/\/\$net2ftp_settings\[\"allowed_ftpserverport\"\] = \"21\";/\$net2ft
 # Finish
 echo "net2ftp is enabled and clipping along!
 
-After creating an FTP Guru (or FTP Filer for private file access also)
+After creating an FTP VIP (or FTP Filer for private file access also)
 
-Login at http://net2ftp.${guruURI}
+Login at http://net2ftp.${vipURI}
 "
diff --git a/serfs/installnextcloud b/serfs/installnextcloud
--- a/serfs/installnextcloud
+++ b/serfs/installnextcloud
@@ -1,25 +1,25 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs Nextcloud manually from inkisaverb.com/repo and linnks it to ....verb.blue
 
 # All options are optional, but must are sequential, omit last options first.
 
 # How to use:
-## ./installnextcloud [latest/repo] [dbase] [dbuser] [dbpassword]
+## ./installnextcloud [latest/repo (optional, default latest, needed for following settings)] [dbase] [dbuser] [dbpassword]
 
 # Eg:
 ## ./installnextcloud repo
 ## ./installnextcloud latest bestdbase trump besteverpass
 
 
-
 CVAPPNAME=nextcloud
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
+. /opt/verb/conf/sitemailpath
 
 LATREP=$1
 DBASE=$2
@@ -29,13 +29,79 @@ CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')
 
 # Check if already installed
 ## Config
-if [ -f /var/local/verb/configs/vapp.${CVAPPNAME} ]; then
+if [ -f /opt/verb/conf/vapp.${CVAPPNAME} ]; then
 echo "This is already installed."
 exit 0; fi
 ## Directory
 if [ -d /var/www/vapps/${CVAPPNAME} ]; then
 echo "Nextcloud already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
-exit 22; fi
+exit 8; fi
+
+# Do it
+cd /var/www/vapps
+## Get and unpack
+echo "Getting Nextcloud, this could take a minute or so..."
+### Repo version ('stable' inkVerb recommendation)
+if [ ${LATREP}="repo" ]; then
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+rm -rf nextcloud
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+### Latest Release Candidate version (default)
+elif [ -z ${1} ] || [ ${LATREP}="latest" ]; then
+wget https://download.nextcloud.com/server/daily/latest.tar.bz2
+if [ ! -f latest.tar.bz2 ]; then
+echo "Can't download Nextcloud. I quit."
+exit 4; fi
+
+rm -rf nextcloud
+tar -xvjf latest.tar.bz2
+rm -f latest.tar.bz2
+fi
+## Install it
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/html/blue.nc; wait
+## Run the Nextcloud script
+/opt/verb/donjon/nextcloudprep.sh; wait
+## Verify ownership
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
+
+## Set up cron for updates (manage the crontab files directly)
+echo '*/15 * * * *  www-data php -f /var/www/vapps/nextcloud/cron.php' > /etc/cron.d/nextcloud
+chmod 0644 /etc/cron.d/nextcloud
+
+#Okay way, not best
+### See this thread: https://stackoverflow.com/questions/4880290/how-do-i-create-a-crontab-through-a-script
+#echo '*/15  *  *  *  * php -f /var/www/vapps/nextcloud/cron.php' > /var/spool/cron/crontabs/www-data
+#chown /var/spool/cron/crontabs/www-data:crontab www-data
+#chmod 600 /var/spool/cron/crontabs/www-data
+
+### A Python solution that doesn't work (https://github.com/nextcloud/news-updater)
+#apt install -y python3-setuptools
+#cd /var/www/vapps
+#git clone https://github.com/nextcloud/news-updater.git
+#sed -i "s/useCronUpdates.*/useCronUpdates = false/" nextcloud/data/news/config/config.ini
+#echo "python3 -m nextcloud_news_updater /var/www/vapps/nextcloud
+#" > /etc/cron.d/nextcloud
+#chmod 0644 /etc/cron.d/nextcloud
+
+### Good Webcron service, but not compatible with the News plugin
+#echo '*/15  *  *  *  * wget -q -O - \"https://nc.${blueURI}/cron.php?refresh=yes\"' >/dev/null 2>&1
+#" > /etc/cron.d/nextcloud
+#chmod 0644 /etc/cron.d/nextcloud
+
+### Wrong way, doesn't work because cron should not run www-data jobs
+#echo '*/15  *  *  *  * www-data php /var/www/vapps/nextcloud/cron.php' > /etc/cron.d/nextcloud
+#chmod 0644 /etc/cron.d/nextcloud
 
 # Auto database
 if [ -z ${4} ]; then
@@ -45,39 +111,8 @@ DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
 if [ -z ${3} ]; then
 DBUSER=${DBASE}; fi
 
-# Do it
-cd /var/www/vapps
-## Get and unpack
-echo "Getting Nextcloud, this could take a minute or so..."
-### Repo version ('stable' inkVerb recommendation)
-if [ ${LATREP}="repo" ]; then
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-rm -rf nextcloud
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
-### Latest Release Candidate version (default)
-elif [ -z ${1} ] || [ ${LATREP}="latest" ]; then
-wget https://download.nextcloud.com/server/daily/latest.tar.bz2
-if [ ! -f latest.tar.bz2 ]; then
-echo "Can't download Nextcloud. I quit."
-exit 44; fi
-rm -rf nextcloud
-tar -xvjf latest.tar.bz2
-rm -f latest.tar.bz2
-fi
-## Install it
-rm -rf /var/www/html/blue.nextcloud
-ln -sfn /var/www/vapps/${CVAPPNAME} /var/www/html/blue.nextcloud
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
-chown -R www-data:www-data /var/www/html/blue.nextcloud
-## Run the Nextcloud script
-/var/local/verb/donjon/nextcloudprep.sh; wait
-## Set up cron for updates
-echo "*/15  *  *  *  * www-data php -f /var/www/vapps/nextcloud/cron.php" > /etc/cron.d/nextcloud
-#chmod 644 /etc/cron.d/nextcloud
-chmod 755 /etc/cron.d/nextcloud
-
 # Create the database and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
 FLUSH PRIVILEGES;"
@@ -86,7 +121,7 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}
 
 echo "These are setup:
 
@@ -97,8 +132,14 @@ Host: localhost
 
 *Don't make any other changes during the install!
 
-Go to https://nextcloud.${blueURI} to install.
+Go to https://nc.${blueURI} to install.
+
+After installing, do important Admin settings at https://nc.${blueURI}/index.php/settings/admin
+1. Background jobs
+- Cron
+2. Email
+- Server address: smtp.${nameURI} Port: 25 (Send mode: SMTP)
+- From address: Use an email address you set up at https://pfa.${emailTLDURI}/${SITEPFAPATH}
 
 After, you may want to run setnextcloudbfdoff to disable brute force detection in order to allow some client apps to work. You can always turn it on again with setnextcloudbfdon
 "
-
diff --git a/serfs/installoctober b/serfs/installoctober
--- a/serfs/installoctober
+++ b/serfs/installoctober
@@ -1,13 +1,13 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs OctoberCMS as a vapp with www/html/DOMAIN.TLD link from newdomain
 ## October actually resides in www/vapps/october.DOMAIN.TLD
 ## This progression is necessary to: 1. keep track of domain contents in www/domains and 2. use standard structure for backups
-## This does not remove any files an ftpguru may have uploaded to the domain's folder
+## This does not remove any files an ftpvip may have uploaded to the domain's folder
 ## Any files conflicting with OctoberCMS will be replaced by the new OctoberCMS installation created by this script
-## Because OctoberCMS is high-maintenance on the developer end, the domain becomes a guru domain and is linked for ftp access in guru/_domains
+## Because OctoberCMS is high-maintenance on the developer end, the domain becomes a vip domain and is linked for ftp access in vip/_domains
 
 # All options after the domain are optional, but are sequential
 
@@ -25,19 +25,29 @@ CLEANNAME=$(echo $DOMAIN | sed -e 's/\.//g')
 
 # Check if already installed
 ## Config
-if [ -f /var/local/verb/configs/vapp.${CVAPPNAME}.${DOMAIN} ]; then
+if [ -f /opt/verb/conf/vapp.${CVAPPNAME}.${DOMAIN} ]; then
 echo "This is already installed."
 exit 0; fi
 ## Directory
 if [ -d /var/www/vapps/${CVAPPNAME}.${DOMAIN} ]; then
 echo "That October site already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
-exit 22; fi
+exit 8; fi
 
 
 # Options
 if [ -z ${1} ]; then
 echo "You must designate a domain."
-exit 22; fi
+exit 8; fi
+
+# Include the config file
+. /opt/verb/conf/sitenameip
+
+# Download and establish October in the server to pre-created domain
+cd /var/www/vapps
+git clone https://github.com/octobercms/install
+if [ ! -d install ]; then
+echo "Can't download OctoberCMS. I quit."
+exit 4; fi
 
 # Auto database
 if [ -z ${4} ]; then
@@ -47,15 +57,6 @@ DBASE=oct$(echo $CLEANNAME | cut -c1-23)$(pwgen -s -1 6); fi
 if [ -z ${3} ]; then
 DBUSER=${DBASE}; fi
 
-# Include the config file
-. /var/local/verb/configs/sitenameip
-
-# Download and establish October in the server to pre-created domain
-cd /var/www/vapps
-git clone https://github.com/octobercms/install
-if [ ! -d install ]; then
-echo "Can't download OctoberCMS. I quit."
-exit 44; fi
 mv install ${CVAPPNAME}.${DOMAIN}
 
 ## Install main themes and plugins
@@ -136,14 +137,14 @@ wget https://github.com/jacoweb/AgencyTheme/archive/master.zip
 unzip master.zip
 rm -f master.zip
 ## Setup links
-rm -f /var/www/html/${DOMAIN}
-ln -s /var/www/vapps/${CVAPPNAME}.${DOMAIN} /var/www/html/${DOMAIN}
-ln -s /var/www/vapps/${CVAPPNAME}.${DOMAIN} /srv/guru/_webapps/
-chown -R www-data:www-data /var/www/html/${DOMAIN}
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}.${DOMAIN}
+rm -f /var/www/html/${DOMAIN}; wait
+ln -s /var/www/vapps/${CVAPPNAME}.${DOMAIN} /var/www/html/${DOMAIN}; wait
+ln -s /var/www/vapps/${CVAPPNAME}.${DOMAIN} /srv/vip/_webapps/; wait
+chown -R www-data:www-data /var/www/html/${DOMAIN}; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}.${DOMAIN}; wait
 
 # Create the database and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
 FLUSH PRIVILEGES;"
@@ -154,7 +155,7 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}.${DOMAIN}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}.${DOMAIN}
 
 # Reset all permissions
 chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}.${DOMAIN}
@@ -169,7 +170,7 @@ Database Name: ${DBASE}
 MySQL Login: ${DBUSER}
 MySQL Password: ${DBPASSWORD}
 
-You also have ftp access to the folder in: guru/_domains/${DOMAIN}
+You also have ftp access to the folder in: vip/_domains/${DOMAIN}
 
 Go to http://${DOMAIN}/index.php to install.
 "
diff --git a/serfs/installorangehrm b/serfs/installorangehrm
--- a/serfs/installorangehrm
+++ b/serfs/installorangehrm
@@ -1,6 +1,6 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs OrangeHRM manually from inkisaverb.com/repo and linnks it to ....verb.blue
 
@@ -13,8 +13,8 @@ set -e
 CVAPPNAME=orangehrm
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
 
 DBASE=$1
 DBUSER=$2
@@ -23,13 +23,33 @@ CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')
 
 # Check if already installed
 ## Config
-if [ -f /var/local/verb/configs/vapp.${CVAPPNAME} ]; then
+if [ -f /opt/verb/conf/vapp.${CVAPPNAME} ]; then
 echo "This is already installed."
 exit 0; fi
 ## Directory
 if [ -d /var/www/vapps/${CVAPPNAME} ]; then
 echo "OrangeHRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
-exit 22; fi
+exit 8; fi
+
+# Download and unpack the latest checked version from inkisaverb.com/repo
+cd /var/www/vapps
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+mkdir -p /var/www/vapps/${CVAPPNAME}/lib/logs
+mkdir -p /var/www/vapps/${CVAPPNAME}/symfony/cache
+mkdir -p /var/www/vapps/${CVAPPNAME}/symfony/log
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/html/red.hrm; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
 
 # Auto database
 if [ -z ${3} ]; then
@@ -39,20 +59,8 @@ DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
 if [ -z ${2} ]; then
 DBUSER=${DBASE}; fi
 
-# Download and unpack the latest checked version from inkisaverb.com/repo
-cd /var/www/vapps
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
-mkdir /var/www/vapps/${CVAPPNAME}/lib/logs
-mkdir /var/www/vapps/${CVAPPNAME}/symfony/cache
-mkdir /var/www/vapps/${CVAPPNAME}/symfony/log
-rm -rf /var/www/html/red.hrm
-ln -s /var/www/vapps/${CVAPPNAME} /var/www/html/red.hrm
-chown -R www-data:www-data /var/www/html/red.hrm
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
-
 # Create the database and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
 FLUSH PRIVILEGES;"
@@ -71,7 +79,7 @@ ufw allow 3306
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}
 
 echo "These are setup:
 
diff --git a/serfs/installowncloud b/serfs/installowncloud
--- a/serfs/installowncloud
+++ b/serfs/installowncloud
@@ -1,6 +1,6 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs ownCloud manually from inkisaverb.com/repo and linnks it to ....verb.blue
 
@@ -18,8 +18,8 @@ set -e
 CVAPPNAME=owncloud
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
 
 DBASE=$1
 DBUSER=$2
@@ -28,13 +28,39 @@ CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')
 
 # Check if already installed
 ## Config
-if [ -f /var/local/verb/configs/vapp.${CVAPPNAME} ]; then
+if [ -f /opt/verb/conf/vapp.${CVAPPNAME} ]; then
 echo "This is already installed."
 exit 0; fi
 ## Directory
 if [ -d /var/www/vapps/${CVAPPNAME} ]; then
 echo "ownCloud already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
-exit 22; fi
+exit 8; fi
+
+# Do it
+cd /var/www/vapps
+## Get and unpack
+echo "Getting ownCloud, this could take a minute or so..."
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+rm -rf owncloud; wait
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+## Install it
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/html/blue.owncloud; wait
+## Run the ownCloud script
+#/opt/verb/donjon/owncloudprep.sh; wait # May be unique to Nextcloud
+## Set up cron for updates
+echo '*/15  *  *  *  * www-data php -f /var/www/vapps/owncloud/cron.php' > /etc/cron.d/owncloud
+chmod 0644 /etc/cron.d/owncloud
 
 # Auto database
 if [ -z ${3} ]; then
@@ -44,27 +70,8 @@ DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
 if [ -z ${2} ]; then
 DBUSER=${DBASE}; fi
 
-# Do it
-cd /var/www/vapps
-## Get and unpack
-echo "Getting ownCloud, this could take a minute or so..."
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-rm -rf owncloud
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
-## Install it
-rm -rf /var/www/html/blue.owncloud
-ln -sfn /var/www/vapps/${CVAPPNAME} /var/www/html/blue.owncloud
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
-chown -R www-data:www-data /var/www/html/blue.owncloud
-## Run the ownCloud script
-#/var/local/verb/donjon/owncloudprep.sh; wait # May be unique to Nextcloud
-## Set up cron for updates
-echo "*/15  *  *  *  * www-data php -f /var/www/vapps/owncloud/cron.php" > /etc/cron.d/owncloud
-#chmod 644 /etc/cron.d/owncloud
-chmod 755 /etc/cron.d/owncloud
-
 # Create the database and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
 FLUSH PRIVILEGES;"
@@ -73,7 +80,7 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}
 
 echo "These are setup:
 
diff --git a/serfs/installpfa b/serfs/installpfa
--- a/serfs/installpfa
+++ b/serfs/installpfa
@@ -1,6 +1,6 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This installs postfix admin
 ## Prerequisite: verbemail IF using a verb domain other than verb.email
@@ -15,18 +15,19 @@ set -e
 ## ./installpfa mysecretpath secure
 
 
+CVAPPNAME=postfixadmin
 # Include the config files
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
-. /var/local/verb/configs/sitemailpass
-. /var/local/verb/configs/sitemailpath
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
+. /opt/verb/conf/sitemailpass
+. /opt/verb/conf/sitemailpath
 
 # Check dependencies and to see if already installed
 if [ ${SITEMAILSTATUS} != "VMAIL_SERVER" ]; then
 echo "
 The email server must be installed first. Run: installpostfix
 "
-exit 22; fi
+exit 8; fi
 if [ ${SITEPFAPATH} = "PFA_NOT_ALLOWED" ]; then
 echo "
 This is a backup email server and PostfixAdmin is not allowed.
@@ -37,35 +38,47 @@ echo "
 PostfixAdmin is already installed.
 "
 exit 0; fi
-if grep -Fq "Webmail Defaults" /var/local/verb/configs/inkdns/zones/${emailTLDURI}.db; then
+if grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}; then
 echo "Proceeding..."; else
 echo "
-Webmail Defaults already declared in the DNS zone file. This won't work.
+Webmail Defaults not declared in the DNS zone file. This won't work.
 "
-exit 22; fi
+exit 8; fi
 
+# Options & secure path
+if [ -n "$1" ]; then
 PFAFOLDER=$1
+else
+PFAFOLDER="$(pwgen -0 5 1)"
+fi
 PFAPASS=$2
 
 # Download from repo
 cd /var/www/email
-/var/local/verb/serfs/inkget postfixadmin; wait
-rm -rf postfixadmin
-/var/local/verb/serfs/vtxzout postfixadmin; wait
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+rm -rf ${CVAPPNAME}
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
 ## Fix a bug
 mkdir -p /var/www/email/postfixadmin/templates_c
 
 # Settings
 ## Whether secure or standard password
 ### If using 'secure', you must set the hash via pfapass
-if [ "${PFAPASS}" != "secure" ]
-then
-    cp /var/local/verb/configs/conflab/vmail/postfixadmin/postfixadmin286-config.inc.php /var/www/email/postfixadmin/config.local.php
+if [ "${PFAPASS}" != "secure" ]; then
+    cp /opt/verb/conf/lab/vmail/postfixadmin/postfixadmin286-config.inc.php /var/www/email/postfixadmin/config.local.php
 fi
 
-if [ "${PFAPASS}" = "secure" ]
-then
-    cp /var/local/verb/configs/conflab/vmail/postfixadmin/postfixadmin286-secure-config.inc.php /var/www/email/postfixadmin/config.local.php
+if [ "${PFAPASS}" = "secure" ]; then
+    cp /opt/verb/conf/lab/vmail/postfixadmin/postfixadmin286-secure-config.inc.php /var/www/email/postfixadmin/config.local.php
 fi
 
 # Settings
@@ -76,27 +89,23 @@ sed -i "s/rcfolder286/${SITERCPATH}/g" /var/www/email/postfixadmin/config.local.
 sed -i "s/pfafolder286/${PFAFOLDER}/g" /var/www/email/postfixadmin/config.local.php
 
 # Copy the branding files
-cp /var/local/verb/configs/conflab/vmail/postfixadmin/pfapics/images/logo-ink.png /var/www/email/postfixadmin/images/
-
-### Should be depreciated after fixed in source
-# Fix the bad password message
-sed -i "s/Your password must contain at least %s character(s)/Your password must contain at least %s letters (A-Z, a-z)/g" /var/www/email/postfixadmin/languages/*
+cp /opt/verb/conf/lab/vmail/postfixadmin/pfapics/images/logo-ink.png /var/www/email/postfixadmin/public/images/
 
 # Set Apache
-cp -R /var/www/html/0ne /var/www/html/${SITEEMAILTLD}.pfa
-ln -s /var/www/email/postfixadmin /var/www/html/${SITEEMAILTLD}.pfa/${PFAFOLDER}
-chown -R www-data:www-data /var/www/html/${SITEEMAILTLD}.pfa
-chown -R www-data:www-data /var/www/email/postfixadmin
-sed -i "s/; Webmail Defaults/; Webmail Defaults\npfa\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\npfa\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /var/local/verb/configs/inkdns/zones/${emailTLDURI}.db
+cp -R /var/www/html/0ne /var/www/html/${SITEEMAILTLD}.pfa; wait
+ln -sfn /var/www/email/postfixadmin/public /var/www/html/${SITEEMAILTLD}.pfa/${PFAFOLDER}; wait
+chown -R www-data:www-data /var/www/html/${SITEEMAILTLD}.pfa; wait
+chown -R www-data:www-data /var/www/email/postfixadmin; wait
+sed -i "s/; Webmail Defaults/; Webmail Defaults\npfa\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\npfa\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}
 a2ensite pfa.${emailTLDURI}
 apache2ctl graceful
 
 # Write the config
-sed -i "s/SITEPFAPATH.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /var/local/verb/configs/sitemailpath
+sed -i "s/SITEPFAPATH.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpath
 
 # inkCert
 ## This adds the declared domain to the end of the "domains =" line
-sed -i "/^domains =/ s/$/, pfa.${emailTLDURI}/" /var/local/verb/configs/inkcert/cli-ini/cli.${emailTLDURI}.ini
+sed -i "/^domains =/ s/$/, pfa.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini
 
 # Finished
 if [ "${PFAPASS}" = "secure" ]
diff --git a/serfs/installrc b/serfs/installrc
--- a/serfs/installrc
+++ b/serfs/installrc
@@ -1,6 +1,6 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This installs roundcube
 ## Prerequisite: verbemail IF using a verb domain other than verb.email
@@ -18,18 +18,19 @@ set -e
 ## ./installrc easy mysecretpath
 
 
+CVAPPNAME=roundcube
 # Include the config files
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
-. /var/local/verb/configs/sitemailpass
-. /var/local/verb/configs/sitemailpath
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
+. /opt/verb/conf/sitemailpass
+. /opt/verb/conf/sitemailpath
 
 # Check dependencies and to see if already installed
 if [ ${SITEMAILSTATUS} != "VMAIL_SERVER" ]; then
 echo "
 The email server must be installed first. Run: installpostfix
 "
-exit 22; fi
+exit 8; fi
 if [ ${SITERCPATH} = "RC_NOT_ALLOWED" ]; then
 echo "
 This is a backup email server and Roundcube is not allowed.
@@ -44,26 +45,40 @@ if [ ${SITEMAILSTATUS} = "EMAIL_NOT_INSTALLED" ]; then
 echo "
 This is a backup email server and Roundcube is not allowed.
 "
-exit 22; fi
-if grep -Fq "Webmail Defaults" /var/local/verb/configs/inkdns/zones/${emailTLDURI}.db; then
+exit 8; fi
+if grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}; then
 echo "Proceeding..."; else
 echo "
-Webmail Defaults already declared in the DNS zone file. This won't work.
+Webmail Defaults not declared in the DNS zone file. This won't work.
 "
-exit 22; fi
+exit 8; fi
 
+# Security & path
+if [ -n "$1" ]; then
 RCFOLDER=$1
+else
+RCFOLDER="$(pwgen -0 5 1)"
+fi
 RCPASSGEN=$(pwgen -s -1 5)
 DESSALTGEN=$(pwgen -s -1 24)
 
 # Get inkVerb's latest and install
 cd /var/www/email
-/var/local/verb/serfs/inkget roundcube; wait
-rm -rf roundcube
-/var/local/verb/serfs/vtxzout roundcube; wait
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+rm -rf ${CVAPPNAME}
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
 
 # Create the MySQL database and user
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  rcmail;
 GRANT ALL PRIVILEGES ON rcmail.* TO 'rcmailusr'@'localhost' IDENTIFIED BY 'rcpass${RCPASSGEN}';
 FLUSH PRIVILEGES;"
@@ -72,14 +87,14 @@ FLUSH PRIVILEGES;"
 cp -R /var/www/html/0ne /var/www/html/${SITEEMAILTLD}.rc
 ln -sfn /var/www/email/roundcube /var/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
 chown -R www-data:www-data /var/www/html/${SITEEMAILTLD}.rc
-sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /var/local/verb/configs/inkdns/zones/${emailTLDURI}.db
+sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}
 a2ensite rc.${emailTLDURI}
 apache2ctl graceful
 
 
 # inkCert
 ## This adds the declared domain to the end of the "domains =" line
-sed -i "/^domains =/ s/$/, rc.${emailTLDURI}/" /var/local/verb/configs/inkcert/cli-ini/cli.${emailTLDURI}.ini
+sed -i "/^domains =/ s/$/, rc.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini
 
 # Roundcube system apps
 apt install -y \
@@ -87,8 +102,7 @@ apt install -y \
   php-mail-mimedecode \
   php-mime-type \
   php-mail-mime \
-  php7.0-intl \
-  php7.0-zip \
+  php-ldap \
   libpspell-dev
 ## The following dependencies often want to be installed after libpspell-dev, so do it differently
 wait
@@ -103,8 +117,8 @@ apache2ctl graceful
 wait
 
 # Settings
-cp /var/local/verb/configs/conflab/vmail/roundcube/config/roundcube286-config.inc.php /var/www/email/roundcube/config/config.inc.php
-cp /var/local/verb/configs/conflab/vmail/roundcube/config/roundcube286-defaults.inc.php /var/www/email/roundcube/config/defaults.inc.php
+cp /opt/verb/conf/lab/vmail/roundcube/config/roundcube286-config.inc.php /var/www/email/roundcube/config/config.inc.php
+cp /opt/verb/conf/lab/vmail/roundcube/config/roundcube286-defaults.inc.php /var/www/email/roundcube/config/defaults.inc.php
 sed -i "s/emailTLDURI286/${emailTLDURI}/g" /var/www/email/roundcube/config/config.inc.php
 sed -i "s/emailTLDURI286/${emailTLDURI}/g" /var/www/email/roundcube/config/defaults.inc.php
 sed -i "s/nameURI286/${nameURI}/g" /var/www/email/roundcube/config/config.inc.php
@@ -118,27 +132,27 @@ sed  -i "s/rcfolder286/${RCFOLDER}/g" /var/www/email/postfixadmin/config.inc.php
 fi
 
 # Copy the branding files
-cp /var/local/verb/configs/conflab/vmail/roundcube/roundcubepics/skins/larry/images/verbink_logo.png /var/www/email/roundcube/skins/larry/images/
-cp /var/local/verb/configs/conflab/vmail/roundcube/roundcubepics/verbink_logo.png /var/www/email/roundcube/
-cp /var/local/verb/configs/conflab/vmail/roundcube/roundcubepics/skins/larry/images/watermark.jpg /var/www/email/roundcube/skins/larry/images/
-cp /var/local/verb/configs/conflab/vmail/roundcube/roundcubepics/skins/larry/images/favicon.ico /var/www/email/roundcube/skins/larry/images/
-cp /var/local/verb/configs/conflab/vmail/roundcube/roundcubepics/favicon.ico /var/www/email/roundcube/
+cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/verbink_logo.png /var/www/email/roundcube/skins/larry/images/
+cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/verbink_logo.png /var/www/email/roundcube/
+cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/watermark.jpg /var/www/email/roundcube/skins/larry/images/
+cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/favicon.ico /var/www/email/roundcube/skins/larry/images/
+cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/favicon.ico /var/www/email/roundcube/
 
 # Own
 chown -R www-data:www-data /var/www/email/roundcube
 
 # Set the config for backup
-sed -i "s/SITERCPASSAPG.*/SITERCPASSAPG=\"${RCPASSGEN}\"/g" /var/local/verb/configs/sitemailpass
-sed -i "s/SITERCPATH.*/SITERCPATH=\"${RCFOLDER}\"/g" /var/local/verb/configs/sitemailpath
+sed -i "s/SITERCPASSAPG.*/SITERCPASSAPG=\"${RCPASSGEN}\"/g" /opt/verb/conf/sitemailpass
+sed -i "s/SITERCPATH.*/SITERCPATH=\"${RCFOLDER}\"/g" /opt/verb/conf/sitemailpath
 
 # Set up plugins that Composer broke
 cd /var/www/email/roundcube/plugins/
 if [ ! -d "/var/www/email/roundcube/plugins/authres_status" ]; then
-cp /var/local/verb/configs/conflab/vmail/roundcube/authres_status.vtxz .
-/var/local/verb/serfs/vtxzout authres_status; wait; fi
+cp /opt/verb/conf/lab/vmail/roundcube/authres_status.vtxz .
+/opt/verb/serfs/vtxzout authres_status; wait; fi
 if [ ! -d "/var/www/email/roundcube/plugins/contextmenu" ]; then
-cp /var/local/verb/configs/conflab/vmail/roundcube/contextmenu.vtxz .
-/var/local/verb/serfs/vtxzout contextmenu; wait; fi
+cp /opt/verb/conf/lab/vmail/roundcube/contextmenu.vtxz .
+/opt/verb/serfs/vtxzout contextmenu; wait; fi
 
 # Sledgehammertime (Composer Plugins)
 ## This is excerpted from installrcinkplugins
@@ -150,6 +164,12 @@ cp composer.json-dist composer.json
 # Causing problems, reactivate when they decide on a minimum version number that doesn't exist in the future
 #sed -i '/\"require\": {/ a\
 #        \"johndoh\/contextmenu\": \"dev-master\",' composer.json
+sed -i '/\"require\": {/ a\
+        \"pear-pear.php.net\/net_ldap2\": \"dev-master\",' composer.json
+sed -i '/\"require\": {/ a\
+        \"kolab\/Net_LDAP3\": \"dev-master\",' composer.json
+sed -i '/\"require\": {/ a\
+        \"angrychimp\/php-dkim\": \"dev-master\",' composer.json
 sed -i '/\"require\": {/ a\
         \"roundcube\/authres_status\": \"dev-master",' composer.json
 sed -i '/\"require\": {/ a\
diff --git a/serfs/installsuitecrm b/serfs/installsuitecrm
--- a/serfs/installsuitecrm
+++ b/serfs/installsuitecrm
@@ -1,6 +1,6 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs the current verified version of suiteCRM from inkisaverb.com/repo to crm.your-name.verb.red
 
@@ -13,7 +13,7 @@ set -e
 CVAPPNAME=suitecrm
 
 # Include the config
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/siteurilist
 
 DBASE=$1
 DBUSER=$2
@@ -22,13 +22,36 @@ CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')
 
 # Check if already installed
 ## Config
-if [ -f /var/local/verb/configs/vapp.${CVAPPNAME} ]; then
+if [ -f /opt/verb/conf/vapp.${CVAPPNAME} ]; then
 echo "This is already installed."
 exit 0; fi
 ## Directory
 if [ -d /var/www/vapps/${CVAPPNAME} ]; then
 echo "SuiteCRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
-exit 22; fi
+exit 8; fi
+
+# Include the config file
+. /opt/verb/conf/sitenameip
+
+# This does not create a database, only an administrator since suiteCRM will create that automatically
+
+# Download and unpack the latest checked version from inkisaverb.com/repo
+cd /var/www/vapps
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+cd /var/www/html
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/html/red.crm; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
 
 # Auto database
 if [ -z ${3} ]; then
@@ -38,23 +61,8 @@ DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
 if [ -z ${2} ]; then
 DBUSER=${DBASE}; fi
 
-# Include the config file
-. /var/local/verb/configs/sitenameip
-
-# This does not create a database, only an administrator since suiteCRM will create that automatically
-
-# Download and unpack the latest checked version from inkisaverb.com/repo
-cd /var/www/vapps
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
-cd /var/www/html
-rm -rf red.crm
-ln -s /var/www/vapps/${CVAPPNAME} /var/www/html/red.crm
-chown -R www-data:www-data /var/www/html/red.crm
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
-
 # Create the database user and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON *.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}' WITH GRANT OPTION;
 FLUSH PRIVILEGES;"
@@ -63,7 +71,7 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}
 
 echo "These are setup:
 
diff --git a/serfs/installwp b/serfs/installwp
--- a/serfs/installwp
+++ b/serfs/installwp
@@ -1,11 +1,11 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs WordPress as a vapp with www/html/DOMAIN.TLD link from adddomain
 ## WordPress actually resides in www/vapps/wp.DOMAIN.TLD
 ## This progression is necessary to: 1. keep track of domain contents in www/domains and 2. use standard structure for backups
-## This does not remove any files an ftpguru may have uploaded to the domain's folder
+## This does not remove any files an ftpvip may have uploaded to the domain's folder
 ## Any files conflicting with WordPress will be replaced by the new WordPress installation created by this script
 ## The domain will automatically be added with DKIM credentials if it has not been already
 ## This will NOT run inkCert for the domain, but inkCert will be prepped at least and used if inkCert certs already exist.
@@ -28,10 +28,10 @@ CLEANNAME=$(echo $DOMAIN | sed -e 's/\.//g')
 # Basic credential check
 if [ -z ${1} ]; then
 echo "You must designate a domain. Read the How to use. Can't continue."
-exit 22; fi
+exit 8; fi
 # Check if already installed
 ## Config
-if [ -f /var/local/verb/configs/vapp.${CVAPPNAME}.${DOMAIN} ]; then
+if [ -f /opt/verb/conf/vapp.${CVAPPNAME}.${DOMAIN} ]; then
 echo "This is already installed."
 exit 0; fi
 ## Directory
@@ -41,9 +41,24 @@ exit 0; fi
 
 # Domain presence check
 if [ ! -d "/var/www/domains/${DOMAIN}" ]; then
-/var/local/verb/serfs/adddomain ${DOMAIN}
+/opt/verb/serfs/adddomain ${DOMAIN}
 wait
 fi
+
+# Download and establish wordpress in the server to pre-created domain
+cd /var/www/vapps
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+rm -rf ${CVAPPNAME}
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
 
 # Auto database
 if [ -z ${4} ]; then
@@ -51,26 +66,17 @@ DBPASSWORD=$(pwgen -s -1 10); fi
 if [ -z ${2} ]; then
 DBASE=wp$(echo $CLEANNAME | cut -c1-24)$(pwgen -s -1 6); fi
 if [ -z ${3} ]; then
-DBUSER=${DBASE}
-fi
+DBUSER=${DBASE}; fi
 
-# Download and establish wordpress in the server to pre-created domain
-cd /var/www/vapps
-wget https://wordpress.org/latest.tar.gz
-if [ ! -f latest.tar.gz ]; then
-echo "Can't download WordPress. I quit."
-exit 44; fi
-tar -xvf latest.tar.gz
-rm -f latest.tar.gz
-mv wordpress ${CVAPPNAME}.${DOMAIN}
+mv ${CVAPPNAME} ${CVAPPNAME}.${DOMAIN}
 rm -f /var/www/html/${DOMAIN}
 ln -sfn /var/www/vapps/${CVAPPNAME}.${DOMAIN} /var/www/html/${DOMAIN}
-ln -sfn /var/www/vapps/${CVAPPNAME}.${DOMAIN} /srv/guru/_webapps/
-chown -R www-data:www-data /var/www/html/${DOMAIN}
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}.${DOMAIN}
+ln -sfn /var/www/vapps/${CVAPPNAME}.${DOMAIN} /srv/vip/_webapps/; wait
+chown -R www-data:www-data /var/www/html/${DOMAIN}; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}.${DOMAIN}; wait
 
 # Create the database and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
 FLUSH PRIVILEGES;"
@@ -79,7 +85,7 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}.${DOMAIN}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}.${DOMAIN}
 
 # Put the settings in the WordPress config file
 cd wp.${DOMAIN}
diff --git a/serfs/installwpinkblog b/serfs/installwpinkblog
--- a/serfs/installwpinkblog
+++ b/serfs/installwpinkblog
@@ -1,6 +1,6 @@
 #!/bin/sh
 #inkVerbSerf! verb.ink
-set -e
+#set -e
 
 # This downloads and installs WordPress to blog.NAME.verb.ink
 ## WordPress actually resides in www/vapps/wp.inkblog
@@ -12,9 +12,10 @@ set -e
 
 
 CVAPPNAME=wp.inkblog
+# "wp" is the normal app, so it must be specified when retrieving from the repo
 
 # Include the config
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/siteurilist
 
 DBASE=$1
 DBUSER=$2
@@ -22,13 +23,28 @@ DBPASSWORD=$3
 CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')
 
 # Check for existing inkblog
-. /var/local/verb/configs/siteinstallstatus
+. /opt/verb/conf/siteinstallstatus
 if [ "${INKblog}" != "NOT_YET" ]; then
 echo "Um... How do I say this...
 Your blog at blog.${inkURI} already has ${INKblog} installed. This just isn't going to work.
 "
 exit 0
 fi
+
+# Download and establish wordpress in the server to pre-created domain
+cd /var/www/vapps
+/opt/verb/serfs/inkget wp; wait
+### Check
+/opt/verb/serfs/inkget wp check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f wp.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+rm -rf wp
+/opt/verb/serfs/vtxzout wp; wait
 
 # Auto database
 if [ -z ${4} ]; then
@@ -38,23 +54,14 @@ DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
 if [ -z ${3} ]; then
 DBUSER=${DBASE}; fi
 
-# Download and establish wordpress in the server to pre-created domain
-cd /var/www/vapps
-wget https://wordpress.org/latest.tar.gz
-if [ ! -f latest.tar.gz ]; then
-echo "Can't download WordPress. I quit."
-exit 44; fi
-tar -xvf latest.tar.gz
-rm -f latest.tar.gz
-mv wordpress ${CVAPPNAME}
-rm -rf /var/www/html/ink.blog
-ln -sfn /var/www/vapps/${CVAPPNAME} /var/www/html/ink.blog
-ln -sfn /var/www/vapps/${CVAPPNAME} /srv/guru/_webapps/
-chown -R www-data:www-data /var/www/html/ink.blog
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
+mv wp ${CVAPPNAME}; wait
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+ln -sfn /var/www/vapps/${CVAPPNAME} /srv/vip/_webapps/; wait
+chown -R www-data:www-data /var/www/html/ink.blog; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
 
 # Create the database and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
 FLUSH PRIVILEGES;"
@@ -63,10 +70,10 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}
 
-# Guru domain
-ln -s /var/www/html/ink.blog /srv/guru/_domains/
+# VIP domain
+ln -s /var/www/html/ink.blog /srv/vip/_domains/
 
 # Put the settings in the WordPress config file
 cd ${CVAPPNAME}
@@ -97,28 +104,28 @@ sed -i "s/define('NONCE_SALT',       'put your unique phrase here');/define('NON
 chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
 
 # Set up the Apache config
-cp /var/local/verb/configs/site-files/conf/blog.${inkURI}.conf-wpblg /etc/apache2/sites-available/blog.${inkURI}.conf
+cp /opt/verb/conf/site-files/conf/blog.${inkURI}.conf-wpblg /etc/apache2/sites-available/blog.${inkURI}.conf
 apache2ctl graceful
 ## inkCert SSL certs
 ### Not setup
-if grep -Fq "INKCERTED=NO" /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${inkURI}; then
+if grep -Fq "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
 echo "FYI: inkCert is not yet setup for ${inkURI}."
 fi
 ### inkCert-LE DONE
-if grep -Fq "INKCERTED=DONE_LE" /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${inkURI}; then
+if grep -Fq "INKCERTED=DONE_LE" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
 echo "inkCert-LE is already setup for ${inkURI}. Updating the Apache configs..."
-/var/local/verb/serfs/inkcertaddallle ${inkURI}
+/opt/verb/serfs/inkcertaddallle ${inkURI}
 wait
 fi
 ### inkCert-IC DONE
-if grep -Fq "INKCERTED=DONE_IC" /var/local/verb/configs/inkcert/cli-ini/siteinkcert.${inkURI}; then
+if grep -Fq "INKCERTED=DONE_IC" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${inkURI}; then
 echo "inkCert-IC is already setup for ${inkURI}. Updating the Apache configs..."
-/var/local/verb/serfs/inkcertadd blog.${inkURI}
+/opt/verb/serfs/inkcertadd blog.${inkURI}
 wait
 fi
 
 # Set the site-wide inkblog config
-sed -i "s/INKblog=.*/INKblog=\"WordPress\"/g" /var/local/verb/configs/siteinstallstatus
+sed -i "s/INKblog=.*/INKblog=\"WordPress\"/g" /opt/verb/conf/siteinstallstatus
 
 # Reset all permissions
 chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
