Normal vrk station updates

diff --git a/serfs/installnextcloud b/serfs/installnextcloud
--- a/serfs/installnextcloud
+++ b/serfs/installnextcloud
@@ -7,7 +7,12 @@ set -e
 # All options are optional, but must are sequential, omit last options first.
 
 # How to use:
-## ./installnextcloud [dbase] [dbuser] [dbpassword]
+## ./installnextcloud [latest/repo] [dbase] [dbuser] [dbpassword]
+
+# Eg:
+## ./installnextcloud repo
+## ./installnextcloud latest bestdbase trump besteverpass
+
 
 
 CVAPPNAME=nextcloud
@@ -16,14 +21,15 @@ CVAPPNAME=nextcloud
 . /var/local/verb/configs/sitenameip
 . /var/local/verb/configs/siteurilist
 
-DBASE=$1
-DBUSER=$2
-DBPASSWORD=$3
+LATREP=$1
+DBASE=$2
+DBUSER=$3
+DBPASSWORD=$4
 CLEANNAME=$(echo $CVAPPNAME | sed -e 's/\.//g')
 
 # Check if already installed
 ## Config
-if [ -f /var/local/verb/configs/verbapp.${CVAPPNAME} ]; then
+if [ -f /var/local/verb/configs/vapp.${CVAPPNAME} ]; then
 echo "This is already installed."
 exit 0; fi
 ## Directory
@@ -32,27 +38,43 @@ echo "Nextcloud already exists in the system. If it isn't working, look deeper o
 exit 22; fi
 
 # Auto database
-if [ -z $3 ]; then
+if [ -z ${4} ]; then
 DBPASSWORD=$(pwgen -s -1 10); fi
-if [ -z $1 ]; then
+if [ -z ${2} ]; then
 DBASE=${CLEANNAME}$(pwgen -s -1 6); fi
-if [ -z $2 ]; then
+if [ -z ${3} ]; then
 DBUSER=${DBASE}; fi
 
 # Do it
 cd /var/www/vapps
 ## Get and unpack
-/var/local/verb/serfs/inkget ${CVAPPNAME}.current
-unzip ${CVAPPNAME}.current.zip
-rm -f ${CVAPPNAME}.current.zip
+echo "Getting Nextcloud, this could take a minute or so..."
+### Repo version ('stable' inkVerb recommendation)
+if [ ${LATREP}="repo" ]; then
+/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
+rm -rf nextcloud
+/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
+### Latest Release Candidate version (default)
+elif [ -z ${1} ] || [ ${LATREP}="latest" ]; then
+wget https://download.nextcloud.com/server/daily/latest.tar.bz2
+if [ ! -f latest.tar.bz2 ]; then
+echo "Can't download Nextcloud. I quit."
+exit 44; fi
+rm -rf nextcloud
+tar -xvjf latest.tar.bz2
+rm -f latest.tar.bz2
+fi
+## Install it
 rm -rf /var/www/html/blue.nextcloud
 ln -sfn /var/www/vapps/${CVAPPNAME} /var/www/html/blue.nextcloud
 chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
 chown -R www-data:www-data /var/www/html/blue.nextcloud
 ## Run the Nextcloud script
-/var/local/verb/donjon/nextcloudprep.sh
+/var/local/verb/donjon/nextcloudprep.sh; wait
 ## Set up cron for updates
 echo "*/15  *  *  *  * www-data php -f /var/www/vapps/nextcloud/cron.php" > /etc/cron.d/nextcloud
+#chmod 644 /etc/cron.d/nextcloud
+chmod 755 /etc/cron.d/nextcloud
 
 # Create the database and credentials
 mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
@@ -64,7 +86,7 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/verbapp.${CVAPPNAME}
+APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}
 
 echo "These are setup:
 
@@ -76,5 +98,7 @@ Host: localhost
 *Don't make any other changes during the install!
 
 Go to https://nextcloud.${blueURI} to install.
+
+After, you may want to run setnextcloudbfdoff to disable brute force detection in order to allow some client apps to work. You can always turn it on again with setnextcloudbfdon
 "
 
